import mongoose from 'mongoose';

const FacilityPptDataSchema = new mongoose.Schema(
  {
    'Service Area': { type: String, default: '', enum: ['Central', 'Eastern', 'Western'], trim: true },
    District: {
      type: String,
      default: '',
      enum: [
        'Alaska',
        'Albuquerque',
        'Atlanta',
        'Boston',
        'Chicago',
        'Cleveland',
        'Denver',
        'Fort Worth',
        'Hawaii/Guam',
        'Houston',
        'Indianapolis',
        'Jacksonville',
        'Kansas City',
        'Los Angeles',
        'Memphis',
        'Miami',
        'Minneapolis',
        'New York',
        'Oakland',
        'Salt Lake',
        'Seattle',
        'Washington',
      ],
      trim: true,
    },
    'Facility Type': {
      type: String,
      default: '',
      enum: [
        'Approach Control',
        'Combined Control Facilities',
        'Enroute Centers',
        'Tower',
        'Tower and Approach Control',
      ],
      trim: true,
    },
    Level: { type: Number, default: '', min: 4, max: 12 },
    'Facility ID': { type: String, unique: true, trim: true },
    'Facility Name': { type: String, default: '', trim: true },
    'CPC Target': { type: Number, default: '' },
    'Current # of CPC On-Board': { type: Number, default: '' },
    'CPC on Temp': { type: Number, default: '' },
    'CPC on Long Term Hold': { type: Number, default: '' },
    'Current # of CPC On-Board minus Temps minus LTH': { type: Number, default: '' },
    'Current % CPC to Target': { type: String, default: '' },
    'Training Time Years': { type: Number, default: '' },
    'ATCS in Training': { type: Number, default: '' },
    'ATCS in Training on Long Term Hold': { type: Number, default: '' },
    'ATCS in Training minus LTH': { type: Number, default: '' },
    'Training Success Rate': { type: String, default: '' },
    'Current ATCS in Training Expected to Cert': { type: Number, default: '' },
    'Committed ATCS Inbound': { type: Number, default: '' },
    'Placement List Inbounds': { type: Number, default: '' },
    'Temps Inbound': { type: Number, default: '' },
    'Inbounds Expected to Cert + Temps Inbound': { type: Number, default: '' },
    'Committed ATCS Outbound': { type: Number, default: '' },
    'Placement List Outbounds': { type: Number, default: '' },
    'Temps Outbound': { type: Number, default: '' },
    'Projected Retirements and Other Losses': { type: Number, default: '' },
    'Projected % to Target': { type: String, default: '', trim: true },
    'Possible Gains to National Average': { type: Number, default: '' },
    'Possible Gains to Target': { type: Number, default: '' },
    'ERR Category': { type: String, default: '', enum: ['Category 1', 'Category 2', 'None'], trim: true },
    'Possible Losses': { type: Number, default: '' },
    'Current % CPC to Trainees': { type: String, default: '', trim: true },
    TNE: { type: Number, default: '' },
    AG: { type: Number, default: '' },
    Dev1: { type: Number, default: '' },
    Dev2: { type: Number, default: '' },
    Dev3: { type: Number, default: '' },
    'Dev Total': { type: Number, default: '' },
    CPCIT0: { type: Number, default: '' },
    CPCIT1: { type: Number, default: '' },
    CPCIT2: { type: Number, default: '' },
    CPCIT3: { type: Number, default: '' },
    'CPCIT Total': { type: Number, default: '' },
    'EnRoute or Terminal': { type: String, default: '', enum: ['ER', 'TR'], trim: true },
    HRRegion: { type: String, default: '', enum: ['EA', 'GL', 'NE', 'NM', 'SO', 'SW', 'WP'], trim: true },
    CoreAirport: { type: String, default: '', enum: ['No', 'Yes'], trim: true },
    Type: { type: Number, default: '', min: 2, max: 9 },
  },
  { collection: 'pptdata', timestamps: true }
);

export default mongoose.models.FacilityPptData || mongoose.model('FacilityPptData', FacilityPptDataSchema);
