import mongoose from 'mongoose';

const PptDateSchema = new mongoose.Schema(
  {
    'Service Area': { type: String, default: '' },
    District: { type: String, default: '' },
    'Facility Type': { type: String, default: '' },
    Level: { type: Number, default: '' },
    'Facility ID': { type: String, unique: true, default: 'Updated', requred: true },
    'Facility Name': { type: String, default: '', required: true },
    'CPC Target': { type: Number, default: '' },
    'Current # of CPC On-Board': { type: Number, default: '' },
    'CPC on Temp': { type: Number, default: '' },
    'CPC on Long Term Hold': { type: Number, default: '' },
    'Current # of CPC On-Board minus Temps minus LTH': { type: Number, default: '' },
    'Current % CPC to Target': { type: String, default: '' },
    'Training Time Years': { type: Number, default: '' },
    'ATCS in Training': { type: Number, default: '' },
    'ATCS in Training on Long Term Hold': { type: Number, default: '' },
    'ATCS in Training minus LTH': { type: Number, default: '' },
    'Training Success Rate': { type: String, default: '' },
    'Current ATCS in Training Expected to Cert': { type: Number, default: '' },
    'Committed ATCS Inbound': { type: Number, default: '' },
    'Placement List Inbounds': { type: Number, default: '' },
    'Temps Inbound': { type: Number, default: '' },
    'Inbounds Expected to Cert + Temps Inbound': { type: Number, default: '' },
    'Committed ATCS Outbound': { type: Number, default: '' },
    'Placement List Outbounds': { type: Number, default: '' },
    'Temps Outbound': { type: Number, default: '' },
    'Projected Retirements and Other Losses': { type: Number, default: '' },
    'Projected % to Target': { type: String, default: '' },
    'Possible Gains to National Average': { type: Number, default: '' },
    'Possible Gains to Target': { type: Number, default: '' },
    'ERR Category': { type: String, default: '' },
    'Possible Losses': { type: Number, default: '' },
    'Current % CPC to Trainees': { type: String, default: '' },
    TNE: { type: Number, default: '' },
    AG: { type: Number, default: '' },
    Dev1: { type: Number, default: '' },
    Dev2: { type: Number, default: '' },
    Dev3: { type: Number, default: '' },
    'Dev Total': { type: Number, default: '' },
    CPCIT0: { type: Number, default: '' },
    CPCIT1: { type: Number, default: '' },
    CPCIT2: { type: Number, default: '' },
    CPCIT3: { type: Number, default: '' },
    'CPCIT Total': { type: Number, default: '' },
    'EnRoute or Terminal': { type: String, default: '' },
    HRRegion: { type: String, default: '' },
    CoreAirport: { type: String, default: '' },
    Type: { type: Number, default: '' },
  },
  { collection: 'pptdata', timestamps: true }
);

export default mongoose.models.PptDate || mongoose.model('PptDate', PptDateSchema);
